# Site settings
author: SHAYLA WHITE
title: The Goddess of Code
header-img: img/home-bg.png
email: shayladwhite1@gmail.com
copyright_name: SHAYLA WHITE
description: > # this means to ignore newlines until "baseurl:"
  Half Goddess Half Code-Heart·ed
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: dopezzz_
github_username:  ShaylaWhite

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
